#!/usr/bin/env bash
export FIFO_UEBERZUG="/tmp/lf-ueberzug-${PPID}"

function cleanup {
  rm "$FIFO_UEBERZUG" 2> /dev/null
  pkill -KILL -P $$
}

mkfifo "$FIFO_UEBERZUG"
trap cleanup EXIT
tail --follow "$FIFO_UEBERZUG" | ueberzug layer --silent --parser bash &

tmp="$(mktemp)"
lf -last-dir-path="$tmp" "$@"
if [ -f "$tmp" ]; then
  dir="$(cat "$tmp")"
  rm -f "$tmp"
  if [ -d "$dir" ]; then
    if [ "$dir" != "$(pwd)" ]; then
      cd "$dir"
    fi
  fi
fi
