#!/usr/bin/env bash

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

if [ "$(hostname)" = "yoga" ]; then
    polybar i3_yoga_m1 &
    polybar i3_yoga_m2 &
    polybar i3_yoga_m3 &
elif [ "$(hostname)" = "r5" ]; then
    polybar i3_r5_m1 &
    polybar i3_r5_m2 &
elif [ "$(hostname)" = "tp" ]; then
    polybar dwmtp &
fi
