#!/usr/bin/env bash

killall -q polybar
while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

if [ "$(hostname)" = "yoga" ]; then
  BAR="i3_yoga"
elif [ "$(hostname)" = "r5" ]; then
  BAR="i3_r5"
elif [ "$(hostname)" = "tp" ]; then
  BAR="i3_tp"
fi

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload "$BAR" &
  done
else
  polybar --reload "$BAR" &
fi
